# Generated by Django 5.1.5 on 2025-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_remove_bus_filled_seats_bus_available_seats_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='booked_buses',
            field=models.ManyToManyField(blank=True, related_name='passenger', to='bus.bus'),
        ),
    ]
