# Generated by Django 5.1.5 on 2025-02-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_passenger_booked_buses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='booked_buses',
        ),
    ]
