# Generated by Django 5.1.5 on 2025-02-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_passenger_booked_buses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passenger',
        ),
    ]
