# Generated by Django 5.1.5 on 2025-02-11 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_details', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=15)),
                ('cost', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('filled_seats', models.IntegerField()),
                ('start_time', models.DateTimeField(max_length=32)),
                ('end_time', models.DateTimeField(max_length=32)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='bus.bus_stop')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departuress', to='bus.bus_stop')),
            ],
        ),
    ]
