# Generated by Django 5.1.5 on 2025-02-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='filled_seats',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='max_capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bus_stop',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
