# Generated by Django 5.1.5 on 2025-02-11 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_bus_bus_details_alter_bus_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 18, 28, 32, 168319), max_length=32),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 18, 28, 32, 168319), max_length=32),
        ),
    ]
