# Generated by Django 5.1.5 on 2025-02-11 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_alter_bus_end_time_alter_bus_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 18, 29, 45, 13558), max_length=32),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 18, 29, 45, 13558), max_length=32),
        ),
    ]
