# Generated by Django 5.1.5 on 2025-02-12 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_alter_bus_end_time_alter_bus_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='filled_seats',
        ),
        migrations.AddField(
            model_name='bus',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 21, 59, 2, 774011), max_length=32),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 21, 59, 2, 774011), max_length=32),
        ),
    ]
