# Generated by Django 5.1.5 on 2025-02-13 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_remove_bus_filled_seats_bus_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 11, 50, 14, 316013), max_length=32),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 11, 50, 14, 316013), max_length=32),
        ),
    ]
