# Generated by Django 5.1.5 on 2025-02-13 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_alter_bus_end_time_alter_bus_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 12, 13, 34, 322205), max_length=32),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 13, 12, 13, 34, 322205), max_length=32),
        ),
    ]
