# Generated by Django 5.1.5 on 2025-02-14 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0014_alter_bus_end_time_alter_bus_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 12, 12, 32, 117297), max_length=32),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 12, 12, 32, 117297), max_length=32),
        ),
    ]
